#OverleveledEnchanter config file

#Change this to true if you want to enable merging enchantments to an uncapped level
#If this is set to false Example: If a player combines 2 unbreaking III books they will receive an unbreaking III book
#If this is set to true Example: If a player combines 2 unbreaking III books they will receive an unbreaking IV book
Uncapped-Merge-Combination: true

#This is the most amount of level a merge in the anvil can cost. If the resulting cost is higher than this one, It will be set to this one.
#The maximum valid value for this is 2147463647, DO NOT put a larger number than the maximum valid one!
#The minimum valid value for this is 1!
Max-Level-Cost: 255

#If this is enabled, whenever an anvil combination is too expensive (cost > 39) the cost will be set to the max-level-cost.
Too-Expensive-Always-Max-Level-Cost: true

#Here you can set the maximum level an enchant can reach.  If an enchanted item has a level above the maximumLevel value and gets into the anvil,
#The resulting item will have it's enchantment's value set to the maximumLevel value.
#Leave the value as -1 to have no limit.  Some enchantments like silk touch and infinity have already their values set to 1, since there is no
#Reason for them to have a higher value than 1.
#Combining level is the highest level that an enchantment can reach through combining same level enchantments.
#It should not have a value lower than 1 except -1 (no cap).
Enchantments:

  power:
    maxLevel: 7
    combining-level: -1

  flame:
    maxLevel: 1
    combining-level: -1  

  infinity:
    maxLevel: 1
    combining-level: 1

  punch:
    maxLevel: 7
    combining-level: -1

  binding_curse:
    maxLevel: 1
    combining-level: 1

  channeling:
    maxLevel: 1
    combining-level: -1

  sharpness:
    maxLevel: 7
    combining-level: -1

  bane_of_arthropods:
    maxLevel: 7
    combining-level: -1

  smite:
    maxLevel: 7
    combining-level: -1

  depth_strider:
    maxLevel: 7
    combining-level: -1

  efficiency:
    maxLevel: 7
    combining-level: -1

  unbreaking:
    maxLevel: 7
    combining-level: -1

  fire_aspect:
    maxLevel: 2
    combining-level: -1

  frost_walker:
    maxLevel: 1
    combining-level: -1

  impaling:
    maxLevel: 7
    combining-level: -1

  knockback:
    maxLevel: 7
    combining-level: -1

  fortune:
    maxLevel: 7
    combining-level: -1

  looting:
    maxLevel: 7
    combining-level: -1

  loyalty:
    maxLevel: 7
    combining-level: -1

  luck_of_the_sea:
    maxLevel: 7
    combining-level: -1

  lure:
    maxLevel: 7
    combining-level: -1

  mending:
    maxLevel: 1
    combining-level: -1

  multishot:
    maxLevel: 1
    combining-level: -1

  respiration:
    maxLevel: 7
    combining-level: -1

  piercing:
    maxLevel: 7
    combining-level: -1

  protection:
    maxLevel: 7
    combining-level: -1

  blast_protection:
    maxLevel: 7
    combining-level: -1

  feather_falling:
    maxLevel: 7
    combining-level: -1

  fire_protection:
    maxLevel: 7
    combining-level: -1

  projectile_protection:
    maxLevel: 7
    combining-level: -1

  quick_charge:
    maxLevel: 5
    combining-level: -1

  riptide:
    maxLevel: 6
    combining-level: -1

  silk_touch:
    maxLevel: 1
    combining-level: 1

  soul_speed:
    maxLevel: 7
    combining-level: -1
    
  sweeping:
    maxLevel: 7
    combining-level: -1

  thorns:
    maxLevel: 7
    combining-level: -1

  vanishing_curse:
    maxLevel: 1
    combining-level: 1
    
  aqua_affinity:
    maxLevel: 7
    combining-level: -1
    
  swift_sneak:
    maxLevel: 7
    combining-level: -1