### Override bukkit.yml and spigot.yml configs
override_spigot_bukkit_configs: true
mob-spawn-range: 3
entity-activation-range:
  tick-inactive-villagers: false
  animals: 10
  monsters: 10
  raiders: 10
  misc: 4
ticks-per:
  animal-spawns: 70
  monster-spawns: 6
spawn-limits:
  monsters: 16
  animals: 8
  water-animals: 8
  ambient: 10

#########


######################################################################################################
# Special functions only available on Spigot 1.14+, won't be activated if server version is below 1.14
######################################################################################################
#Log when the plugin untrack entities
log-to-console: false
log-detailed: false
log-tps:
  enabled: false
  interval: 1200

disable-tick-for-untracked-entities: true
disable-ai-for-untracked-entities: true

fix-ai-previous-update: false

trigger-options:
  #If set to true: optimization takes place every "untrack-ticks" also if tps is not below value specified in "when-tps-below"
  always:
    enabled: true
    #How many ticks between untrack process
    #The untrack process will check for untracked entities by players but still by the server, and untrack them.
    untrack-ticks: 600
  when-tps-below:
    enabled: true
    #if tps are not below this value, the task will not perform the untrack and it will wait for the next run
    value: 18.5
    #How many ticks between untrack process
    #The untrack process will check for untracked entities by players but still by the server, and untrack them.
    untrack-ticks: 450


#frecuency in ticks to check untracked entities
#It will check for players traking entities and will track it again (this is to prevent invisible entities)
check-untracked-entities-frequency: 30

#Distance in blocks to check for players near untracked entities
tracking-range: 35

#Entities with these properties will be ignored from optimization. You should leave this as default
ignore:
  custom-named: true
  invulnerable: false
  drops: true
  itemframes: true
  armorstands: true
  villagers: false

#which worlds do you want these options to be applied
worlds:
  - world
  - world_nether
  - world_the_end
