Template: PetOverlord
Settings:
  Default_Name: Donkey
  Entity_Type: DONKEY
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNjNhOTc2YzA0N2Y0MTJlYmM1Y2IxOTcxMzFlYmVmMzBjMDA0YzBmYWY0OWQ4ZGQ0MTA1ZmNhMTIwN2VkYWZmMyJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
