Template: PetOverlord
Settings:
  Default_Name: Frog
  Entity_Type: FROG
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNTFhODhiNjlkODJkYmNjODVmMDBjZmY4NzAzNzA1Zjk0MDhiY2RkM2E2MWNlZmJmNjdhYTVlZmVlNWQ3N2YzMCJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
