Template: Ridable
Settings:
  Default_Name: Skeleton Horse
  Entity_Type: SKELETON_HORSE
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzI2MThhM2MyNjhjYTM4OGEzOGI4OTMwMTZhYmEyNmY2MjcxNTE5Y2RlMWE2YmJkNTk5Y2RkNjQ3Mjg0M2I3ZiJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
