Template: CombatOverlord
Settings:
  Default_Name: Slime
  Entity_Type: SLIME
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvODk1YWVlYzZiODQyYWRhODY2OWY4NDZkNjViYzQ5NzYyNTk3ODI0YWI5NDRmMjJmNDViZjNiYmI5NDFhYmU2YyJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
