Template: PetOverlord
Settings:
  Default_Name: Turtle
  Entity_Type: TURTLE
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvOTlkNjcxMjU4MmQ2MGEwMDU4ZTRmYmVlMGU4OWRkMDg5ZmJhYmI4MGYwN2U0YTA4NzQ5MDRjOTFiYzQ4ZjA4YSJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
