Template: WitherSkeleton
Settings:
  Default_Name: Wither Skeleton
  Entity_Type: WITHER_SKELETON
  Egg_Texture: eyJ0ZXh0dXJlcyI6eyJTS0lOIjp7InVybCI6Imh0dHA6Ly90ZXh0dXJlcy5taW5lY3JhZnQubmV0L3RleHR1cmUvNzk1M2I2YzY4NDQ4ZTdlNmI2YmY4ZmIyNzNkNzIwM2FjZDhlMWJlMTllODE0ODFlYWQ1MWY0NWRlNTlhOCJ9fX0=
Food:
  item_example:
    Item:
      Material: APPLE
    Saturation: 3.0
    Sound: ENTITY_GENERIC_EAT
    Particle:
      Name: HEART
      Data: ''
